ws_data_sync.field_mapping.*:
  type: config_entity
  label: 'Field Mapping config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    local_field:
      type: sequence
      label: 'Local field'
      sequence:
        type: mapping
        mapping:
          type:
            type: string
            label: Field type
          name:
            type: string
            label: Machine name
    feed:
      type: string
      label: 'Feed'
    webservice:
      type: string
      label: 'Webservice'
