ws_data_sync.webservice.*:
  type: config_entity
  label: 'Webservice config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    url:
      type: string
      label: 'Url'
    type:
      type: string
      label: 'Type'
    format:
      type: string
      label: 'Format'
    authentication:
      type: mapping
      mapping:
        type:
          type: string
          label: 'Auth type'
        credentials:
          type: mapping
          label: 'Authentication credentials'
