<?php

namespace Drupal\ws_data_sync;

use Drupal\Core\Config\Entity\ConfigEntityListBuilder;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\EntityStorageInterface;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Url;
use Symfony\Component\DependencyInjection\ContainerInterface;

/**
 * Provides a listing of Feed entities.
 */
class FeedListBuilder extends ConfigEntityListBuilder {

  /**
   * @var \Symfony\Component\HttpFoundation\Request
   */
  protected $request;

  public function __construct(EntityTypeInterface $entity_type, EntityStorageInterface $storage) {
    parent::__construct($entity_type, $storage);
    $this->request = \Drupal::request();
  }

  /**
   * @inheritDoc
   */
//  public static function createInstance(ContainerInterface $container, EntityTypeInterface $entity_type) {
//    return parent::createInstance($container, $entity_type); // TODO: Change the autogenerated stub
//  }


  /**
   * {@inheritdoc}
   */
  public function buildHeader() {
    $header['label'] = $this->t('Feed');
    $header['id'] = $this->t('Machine name');
    $header['webservice'] = $this->t('Webservice');
    return $header + parent::buildHeader();
  }

  /**
   * {@inheritdoc}
   */
  public function buildRow(EntityInterface $entity) {
    $row['label'] = $entity->label();
    $row['id'] = $entity->id();
    $row['webservice'] = $entity->getWebservice();
    // You probably want a few more properties here...
    return $row + parent::buildRow($entity);
  }

  public function load() {
    return $this->getStorage()->loadByProperties([
      'webservice' => $this->request->get('webservice')
    ]);
  }

  public function getOperations(EntityInterface $entity) {
    $operations = parent::getOperations($entity);

    $operations['edit'] = [
      'title' => $this->t('Edit'),
      'weight' => 10,
      'url' => Url::fromRoute('entity.feed.edit_form', [
        'webservice' => $this->request->get('webservice'),
        'feed' => $entity->id()
      ]),
    ];

    $operations['manage_field_mappings'] = [
      'title' => t('Manage field mappings'),
      'weight' => -100,
      'url' => Url::fromRoute('entity.field_mapping.collection', [
        'webservice' => $this->request->get('webservice'),
        'feed' => $entity->id()
      ]),
    ];

    unset($operations['translate']);

    return $operations;

  }


}
